[theme]
primaryColor = "#3498db"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
port = 8501
enableXsrfProtection = false
enableCORS = false

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true
toolbarMode = "minimal"
